- name: Copy ip address to node1
  hosts: node1
  vars:
    ip_address: 172.31.88.207
  tasks:
   - name: Copy ip address to the nodes
     ansible.builtin.copy:
       content: 'Private ip address of this node is {{ ip_address }}'
       dest: /home/ec2-user/myfile
      
   - name: using debug module
     ansible.builtin.debug:
       var: ip_address
