- name: Copy ip address to node1
  hosts: node1
  tasks:
   - name: Copy ip address to the nodes
     ansible.builtin.copy:
       content: 'Private ip address of this node is 172.31.88.207'
       dest: /home/ec2-user/myfile
      
- name: Copy ip address to node2
  hosts: node2
  tasks:
   - name: Copy ip address to the nodes
     ansible.builtin.copy:
       content: 'Private ip address of this node is 172.31.81.197'
       dest: /home/ec2-user/myfile